[versions]
shadow = "8.3.8"
blossom = "1.3.1"
moddevgradle = "2.0.110"
forgegradle = "[6.0.36,6.2)"
loom = "1.13-SNAPSHOT"
licenser = "0.6.1"

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle" }
loom = { id = "fabric-loom", version.ref = "loom" }
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }