[versions]
shadow = "8.1.1"
blossom = "1.3.1"
forgegradle = "[6.0,6.2)"
loom = "1.3-SNAPSHOT"
licenser = "0.6.1"

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle" }
loom = { id = "fabric-loom", version.ref = "loom" }
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }