blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ â€‹ Ask a question
    url: https://discord.gg/luckperms
    about: We use Discord to provide support for the project. If you have a question, need help, or aren't sure if you've found a bug or not, please come and talk to us there!